version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "blaaiz/maintainers"
    assignees:
      - "blaaiz/maintainers"
    open-pull-requests-limit: 5
    target-branch: "develop"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "blaaiz/maintainers"
    assignees:
      - "blaaiz/maintainers"